version: "3.9"
services:
  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - OLLAMA_API_BASE=https://ollama-latest-ypq1.onrender.com  # <-- use your Render link here
